version: '3.9'
services:
  backend:
    container_name: backend
    build: .
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
  
  proxy:
    container_name: proxy
    image: nginx:1.19.6-alpine
    restart: unless-stopped
    environment:
      WAIT_HOSTS: backend:80
    depends_on:
      - backend
    ports:
      - "443:443"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/:/opt/ssl/

  composer:
    image: composer:2.1.12
    working_dir: /comp
    volumes:
      - "./:/comp"
    command: composer update --ignore-platform-reqs